# Stage 1: Build
FROM eclipse-temurin:17.0.5_8-jre-focal AS build
WORKDIR /app

# Add the JAR file to the container
ADD ./target/*.jar app.jar

# Extract the JAR layers
RUN java -Djarmode=layertools -jar app.jar extract

# Stage 2: Runtime
FROM eclipse-temurin:17.0.5_8-jre-focal
WORKDIR /app

# Copy extracted layers from the build stage
COPY --from=build /app/extracted/dependencies/ ./
COPY --from=build /app/extracted/spring-boot-loader/ ./
COPY --from=build /app/extracted/snapshot-dependencies/ ./
COPY --from=build /app/extracted/application/ ./

# Expose the application port
EXPOSE 8080

# Corrected the ENTRYPOINT syntax by adding a space
ENTRYPOINT ["java", "-jar", "org.springframework.boot.loader.JarLauncher"]
